import { MantineProvider } from "@mantine/core";

import Head from "next/head";
import Navigation from "../components/Navigation";

export default function Home() {
  return (
    <>
      <MantineProvider
        theme={{
          // use custom font in MantineProvider
          fontFamily: "Proxima Nova, sans-serif",
          fontFamily: "Proxima Nova Light, sans-serif",
        }}
      >
        <div>
          <Head>
            <title>Ball&apos;s Blog</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        </div>
        <div>
          <Navigation />
        </div>
      </MantineProvider>
    </>
  );
}
